# src/OC/PlatformBundle/Resources/config/routing.yml

bonbers_platform_home:
    path:      /{page}
    defaults:
        _controller: BONBERSPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d+
    
bonbers_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: BONBERSPlatformBundle:Advert:view
    requirements:
        id: \d+

bonbers_platform_add:
    path:      /add
    defaults:
        _controller: BONBERSPlatformBundle:Advert:add

bonbers_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: BONBERSPlatformBundle:Advert:edit
    requirements:
        id: \d+

bonbers_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: BONBERSPlatformBundle:Advert:delete
    requirements:
        id: \d+